# Generated by Django 2.2.10 on 2020-04-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='fk',
        ),
    ]
